---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: droppedneedle
  namespace: media
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: droppedneedle
  values:
    controllers:
      droppedneedle:
        replicas: 1

        containers:
          app:
            image:
              repository: ghcr.io/habirabbu/droppedneedle
              tag: v2.3.0

            env:
              TZ: "Europe/Belgrade"
              PORT: &port 8688
              SLSKD_DOWNLOADS_PATH: /media/Download/soulseek/complete
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  failureThreshold: 60
                  periodSeconds: 10
            resources:
              requests:
                cpu: 20m
                memory: 512Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: droppedneedle
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nikola.wtf"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: droppedneedle
                port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}-config"
        globalMounts:
          - path: /app/config
          - path: /app/cache
            subPath: cache
      tmp:
        type: emptyDir
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.5.0.10"
            path: "/var/nfs/shared/media"
        globalMounts:
          - path: "/media"
