---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USERNAME }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        renderer-token: "{{ .GRAFANA_RENDERER_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana
