---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: VictoriaMetrics
    type: prometheus
    uid: prometheus
    access: proxy
    isDefault: true
    url: http://vmsingle-vmetrics-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8428
    jsonData:
      prometheusType: Prometheus
      timeInterval: 1m
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://vm-logs-victoria-logs-single-server.monitoring.svc:9428
