---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: kritika
  namespace: kritika
spec:
  name: kritika
  owner: kritika
  cluster:
    name: kritika-pg
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
