---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kritika
  namespace: kritika
spec:
  interval: 1h
  url: https://github.com/home-operations/kritika
  ref:
    commit: d80674859fe3bec530f729ae9a611b152f9ad025
  ignore: |-
    /*
    !/charts/kritika
