---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kritika
  namespace: kritika
spec:
  interval: 1h
  url: https://github.com/home-operations/kritika
  ref:
    commit: 34c7358713b71839e2bcdb60b962aaeca27c1d0e
  ignore: |-
    /*
    !/charts/kritika
