---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kritika
resources:
  - ./externalsecret.yaml
  - ./objectstore.yaml
  - ./postgres.yaml
  - ./database.yaml
  - ./scheduledbackup.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./netpol-canary.yaml
