---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: privado-socks
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: privado-socks-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        gost.yaml: |
          services:
            - name: socks5
              addr: :1080
              handler:
                type: socks5
                chain: privado
              listener:
                type: tcp
          chains:
            - name: privado
              hops:
                - name: privado
                  nodes:
                    - name: privado
                      addr: "{{ .host }}:{{ .port }}"
                      connector:
                        type: socks5
                        auth:
                          username: {{ .username | quote }}
                          password: {{ .password | quote }}
                      dialer:
                        type: tcp
  dataFrom:
    - extract:
        key: privado-socks
