---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-immich
  labels:
    flux.home/helm-defaults: skip
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: ot-operator-standalone
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    redisExporter:
      enabled: true
      image: quay.io/oliver006/redis_exporter
      # renovate: datasource=docker depName=quay.io/oliver006/redis_exporter
      tag: v1.89.0
