---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app manyfold
spec:
  components:
    - ../../../../components/kopiur/volume
    - ../../../../components/kopiur/backup
  targetNamespace: misc
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: miroir-config
      namespace: miroir-system
    - name: external-secrets-stores
      namespace: security
    - name: redis-manyfold
      namespace: database
  path: ./kubernetes/apps/misc/manyfold/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      VOLSYNC_SCHEDULE: "50 0 * * *"
      VOLSYNC_LOCAL_SCHEDULE: "50 3 * * *"
      APP: *app
      VOLSYNC_CLAIM: manyfold
      VOLSYNC_CAPACITY: 20Gi
