---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-image-renderer
  namespace: monitoring
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: grafana-image-renderer
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      grafana-image-renderer:
        containers:
          app:
            image:
              repository: docker.io/grafana/grafana-image-renderer
              tag: v5.10.2
            env:
              TZ: "Europe/Belgrade"
              GOMEMLIMIT: 768MiB
            envFrom:
              - secretRef:
                  name: grafana-image-renderer-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  failureThreshold: 6
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: grafana-image-renderer
        ports:
          http:
            port: *port
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
