---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./namespace.yaml
  - ./chaski/ks.yaml
  - ./cobalt/ks.yaml
  - ./cobalt-web/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./plex/ks.yaml
  - ./jellyfin/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./unpackerr/ks.yaml
  - ./profilarr/ks.yaml
  - ./seerr/ks.yaml
  - ./tautulli/ks.yaml
  - ./plex-trakt-sync/ks.yaml
  - ./shelfmark/ks.yaml
  - ./bookboss/ks.yaml
