---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: home-assistant
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        sysctls:
          - name: net.ipv6.conf.net1.accept_ra
            value: "2"
          - name: net.ipv6.conf.net1.accept_ra_defrtr
            value: "1"
          - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
            value: "64"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - sabnzbd
              namespaces:
                - media
              topologyKey: kubernetes.io/hostname

    controllers:
      home-assistant:
        annotations:
          configmap.reloader.stakater.com/reload: "hass-config"
          secret.reloader.stakater.com/reload: "homeassistant-secrets"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.50.0.210/24", "fd00:50::210/64"],
                "mac": "dc:de:70:dd:f4:9e"
              }]

        replicas: 1

        containers:
          app:
            image:
              repository: quay.io/nklmilojevic/home-assistant
              tag: 2026.7.3@sha256:d3a696ae8ba8333e96038e5e31324eb85541c7c67a0c34e9f2bdaa957eaec838
            env:
              TZ: "Europe/Belgrade"
            envFrom:
              - secretRef:
                  name: homeassistant-secrets
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 2Gi

          openssh:
            image:
              repository: quay.io/nklmilojevic/openssh
              tag: 3.24.1
            env:
              TZ: "Europe/Belgrade"
              PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICrYywYsK/kocVOa48LjaOR2X10g7lwsB1PtkyBJX800 id_ed25519"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: &app home-assistant
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: &port 8123
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
      ssh:
        controller: *app
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.40.0.16"
        ports:
          ssh:
            port: 22
            targetPort: 2222

    route:
      app:
        hostnames:
          - hass.nikola.wtf
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: home-assistant-app
                port: *port

    persistence:
      config:
        existingClaim: home-assistant-config
      config-cache:
        existingClaim: "home-assistant-cache"
        globalMounts:
          - path: /config/.venv
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp

    serviceMonitor:
      home-assistant:
        serviceName: home-assistant-app
        endpoints:
          - port: http
            scheme: http
            path: /api/prometheus
            interval: 30s
            scrapeTimeout: 10s
            bearerTokenSecret:
              name: homeassistant-secrets
              key: HASS_PROMETHEUS_TOKEN
