---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-media
spec:
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: home-assistant-media-bootstrap
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
