---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: misc
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./externalsecret.yaml
  - ./rbac.yaml
  - ./dnsendpoint.yaml
