---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: isponsorblocktv
  labels:
    flux.home/helm-defaults: skip
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: isponsorblocktv
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      isponsorblocktv:
        replicas: 1

        containers:
          app:
            image:
              repository: ghcr.io/dmunozv04/isponsorblocktv
              tag: v2.9.0
            env:
              TZ: "Europe/Belgrade"

    persistence:
      config:
        enabled: true
        type: secret
        name: isponsorblocktv-secret
        globalMounts:
          - path: /app/data/config.json
            subPath: config.json
            readOnly: true
