---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: silence-operator
  dependsOn:
    - name: vmetrics
      namespace: o11y
    - name: silence-operator-crds
      namespace: o11y
  values:
    alertmanagerAddress: http://vmalertmanager-vmetrics-victoria-metrics-k8s-stack:9093
    crds:
      install: false
    networkPolicy:
      enabled: false
