---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  # renovate: registryUrl=http://bjw-s.github.io/helm-charts/
  chartRef:
    kind: OCIRepository
    name: jellyfin
  values:
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimTemplateName: jellyfin

    controllers:
      jellyfin:
        replicas: 1

        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
            env:
              TZ: "Europe/Belgrade"
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_PublishedServerUrl: https://jellyfin.nikola.wtf
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: false
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 200m
                memory: 1Gi
              limits:
                memory: 3Gi

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 105
              - 100
              - 109

    service:
      app:
        controller: jellyfin
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: "10.40.0.7"
        ports:
          http:
            port: *port
          discovery:
            port: 7359
            protocol: UDP

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nikola.wtf"
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: jellyfin
                port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}-config"
      metadata:
        size: 10Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /metadata
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /tmp
                subPath: tmp
              - path: /transcode
                subPath: transcode
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.5.0.10"
            path: "/var/nfs/shared/media"
        globalMounts:
          - path: "/media"
