---
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
dashboards:
  enabled: true
autoDirectNodeRoutes: true
bandwidthManager:
  enabled: true
  bbr: true
bpf:
  datapathMode: netkit
  masquerade: true
  preallocateMaps: true
bpfClockProbe: true
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
cluster:
  id: 1
  name: home-kubernetes
cni:
  exclusive: false
enableIPv4BIGTCP: true
enableRuntimeDeviceDetection: true
endpointRoutes:
  enabled: true
envoy:
  enabled: false
gatewayAPI:
  enabled: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.69.0.0/16
k8sServiceHost: 127.0.0.1
k8sServicePort: 7445
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
pmtuDiscovery:
  enabled: true
socketLB:
  enabled: true
  hostNamespaceOnly: true
operator:
  replicas: 2
  rollOutPods: true
  dashboards:
    enabled: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  relay:
    enabled: true
    rollOutPods: true
  tls:
    auto:
      method: cronJob
      schedule: "0 4 1 * *"
  ui:
    enabled: true
    rollOutPods: true
