---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.37.0
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        !has(status.phase) || status.phase != 'Running'
    - apiVersion: miroir.home-operations.com/v1alpha1
      kind: MiroirNodeGroup
      expr: |-
        status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
