---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=custom.talos-factory depName=siderolabs/talos
    version: v1.13.8
  policy:
    rebootMode: powercycle
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        !has(status.phase) || status.phase != 'Running'
    - apiVersion: miroir.home-operations.com/v1alpha1
      kind: MiroirNodeGroup
      expr: |-
        status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
