---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nut-exporter
  namespace: monitoring
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nut-exporter:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: docker.io/hon95/prometheus-nut-exporter
              tag: "1.2.1"
            env:
              TZ: "Europe/Belgrade"
              HTTP_PATH: "/metrics"
            resources:
              requests:
                cpu: 15m
                memory: 30Mi
    service:
      app:
        controller: nut-exporter
        ports:
          metrics:
            port: 9995
    serviceMonitor:
      nut-exporter:
        serviceName: nut-exporter
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s
            params:
              target:
                - "10.5.0.49:3493"
