---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/embeddingserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: EmbeddingServer
metadata:
  name: text-embeddings-inference
spec:
  env:
    - name: HOSTNAME
      value: "::"
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest@sha256:e04661a70f78b4be988e1bb901e5256d1201381811db1f27c14805e6a848cd50
  model: sentence-transformers/all-MiniLM-L6-v2
  resources:
    requests:
      cpu: 25m
      memory: 512Mi
