---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/embeddingserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: EmbeddingServer
metadata:
  name: text-embeddings-inference
spec:
  env:
    - name: HOSTNAME
      value: "::"
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest@sha256:e0918e6fc9020c7fcef8733f4191f6bffe2f5be44c1e409658be3244dfaf1231
  model: sentence-transformers/all-MiniLM-L6-v2
  resources:
    requests:
      cpu: 25m
      memory: 512Mi
