---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kritik
  namespace: kritik
spec:
  interval: 1h
  url: https://github.com/home-operations/kritik
  ref:
    commit: 4a1c3206434ac137be6dd34844062f0dd0be68e3
  ignore: |-
    /*
    !/charts/kritik
