---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kritik
  namespace: kritik
spec:
  interval: 1h
  url: https://github.com/home-operations/kritik
  ref:
    commit: 09963afb746d3fb1c5e2f1baf3333599cbf620ba
  ignore: |-
    /*
    !/charts/kritik
