---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kritik
  namespace: kritik
spec:
  interval: 1h
  url: https://github.com/home-operations/kritik
  ref:
    commit: b8362bc8fd366f7d18181c8122b6428907a4b571
  ignore: |-
    /*
    !/charts/kritik
