---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kritik
resources:
  - ./externalsecret.yaml
  - ./objectstore.yaml
  - ./postgres.yaml
  - ./database.yaml
  - ./scheduledbackup.yaml
  - ./gitrepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
