---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  # renovate: registryUrl=http://bjw-s.github.io/helm-charts/
  chartRef:
    kind: OCIRepository
    name: prowlarr
  values:
    controllers:
      prowlarr:
        replicas: 1
        containers:
          app:
            image:
              repository: quay.io/nklmilojevic/prowlarr
              tag: 2.5.1.5464@sha256:f324eeb801d3887609af0bc916017d7b23f667df4fa479d2c74552d08940dcc7
            env:
              TZ: "Europe/Belgrade"
            resources:
              requests:
                cpu: 10m
                memory: 192Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: prowlarr
        ports:
          http:
            port: &port 9696

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nikola.wtf"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: prowlarr
                port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}-config"
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.5.0.10"
            path: "/var/nfs/shared/media"
        globalMounts:
          - path: "/media"
