{
 "title": "Immich Overview",
 "description": "A dashboard to visualize current status of immich instance on kubernetes cluster.",
 "tags": [
  "immich",
  "immich-charts"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "NAMESPACE",
    "query": {
     "query": "label_values({service_name=\"immich\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NodeJS Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immich Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{namespace=\"$NAMESPACE\", endpoint=\"http-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_static{namespace=\"$NAMESPACE\", endpoint=\"http-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Immich Health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Immich Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{namespace=\"$NAMESPACE\", endpoint=\"http-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{namespace=\"$NAMESPACE\", endpoint=\"http-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(http_method, http_status_code) (rate(http_server_duration_sum{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}[$__rate_interval])) / avg by(http_method, http_status_code) (rate(http_server_duration_count{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}[$__rate_interval]))",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_duration_count{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\"}[$__rate_interval])) by (http_method, http_status_code)) * $__interval_ms / 1000",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Total Errors (4XX | 5XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(http_method, http_status_code) (increase(http_server_duration_sum{namespace=\"$NAMESPACE\", endpoint=\"metrics-api\", http_status_code=~\"4.*|5.*\"}[$__rate_interval]))",
     "legendFormat": "{{http_method}} {{http_status_code}}"
    }
   ]
  }
 ]
}