---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
  namespace: misc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-secret
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
        uuid: "{{ .uuid }}"
  dataFrom:
    - extract:
        key: forgejo-runner
