---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-endpoint
  namespace: kopiur-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: kopiur-endpoint
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        R2_ENDPOINT: "{{ .R2_ENDPOINT }}"
  dataFrom:
    - extract:
        key: kopiur
