---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
components:
  - ../../components/kopiur/secret
resources:
  - ./namespace.yaml
  - ./external-secrets/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./volsync/ks.yaml
  - ./atuin/ks.yaml
  - ./versitygw/ks.yaml
