---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ha-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: HOMEASSISTANT_TOKEN
      remoteRef:
        key: ha-mcp
        property: token
