---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: ha-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/homeassistant-ai/ha-mcp:8.3.0@sha256:38b3a0b6b6b69d3fd074f958fbf9653ae2d50c8727b4c0dcde640cfa3a638176
  transport: streamable-http
  env:
    - name: HOMEASSISTANT_URL
      value: http://home-assistant-app.home.svc.cluster.local:8123
  secrets:
    - name: ha-mcp-secret
      key: HOMEASSISTANT_TOKEN
  resources:
    requests:
      cpu: 10m
      memory: 192Mi
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          command:
            - ha-mcp-web
          volumeMounts:
            - name: tmpfs
              mountPath: /tmp
      volumes:
        - name: tmpfs
