---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-server
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      matter-server:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-host",
                "namespace": "network",
                "ips": ["10.5.0.245/24", "fd00:5::245/64"],
                "mac": "3a:f2:c8:91:b7:44"
              }]
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
            sysctls:
              - name: net.ipv6.conf.net1.accept_ra
                value: "2"
              - name: net.ipv6.conf.net1.accept_ra_defrtr
                value: "1"
              - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
                value: "64"

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 8.1.0@sha256:170aa093ce91c76cde4cc390918307590f0f5558fcec93f913af3cb019e6562a
            args:
              - --storage-path=/data
              - --primary-interface=net1
              - --log-level=debug
              - --log-level-sdk=info
            env:
              TZ: Europe/Belgrade
              MATTER_SERVER__INSTANCE_NAME: matter-server
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__LOG_LEVEL: info
            securityContext:
              privileged: true
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: matter-server
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nikola.wtf"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: matter-server
                port: *port

    persistence:
      data:
        existingClaim: matter-server-data
      tmp:
        type: emptyDir
