---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 5m
  # renovate: registryUrl=http://bjw-s.github.io/helm-charts/
  chartRef:
    kind: OCIRepository
    name: bazarr
  values:
    controllers:
      bazarr:
        replicas: 1

        containers:
          app:
            image:
              repository: quay.io/nklmilojevic/bazarr
              tag: 1.6.0@sha256:c10d46618be222f33c3fab3aff4a65c24d7ed6acd3098129c50cfb9016afbd21
            env:
              TZ: "Europe/Belgrade"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: bazarr
        ports:
          http:
            port: &port 6767

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nikola.wtf"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: bazarr
                port: *port

    persistence:
      config:
        existingClaim: "{{ .Release.Name }}-config"
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "10.5.0.10"
            path: "/var/nfs/shared/media"
        globalMounts:
          - path: "/media"
