---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petkit-local-media
spec:
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: petkit-local-media-bootstrap
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: miroir
