---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petkit-local-media
spec:
  dataSourceRef:
    apiGroup: kopiur.home-operations.com
    kind: Restore
    name: petkit-local-media
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  storageClassName: miroir
