---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: vmsingle-health
spec:
  compression:
    compressor: zstd
  mover:
    cache:
      capacity: 1Gi
      mode: Persistent
      storageClassName: openebs-hostpath
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  repository:
    kind: ClusterRepository
    name: r2
  retention:
    keepLatest: 3
    keepDaily: 7
  sources:
    - pvc:
        name: vmsingle-health
  volumeSnapshotClassName: miroir
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: vmsingle-health
spec:
  policyRef:
    name: vmsingle-health
  schedule:
    cron: "H 0 * * *"
    timezone: Europe/Belgrade
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/restore_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: vmsingle-health
spec:
  policy:
    onMissingSnapshot: Continue
  source:
    fromPolicy:
      name: vmsingle-health
      offset: 0
  target:
    populator: {}
