---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app appdaemon
spec:
  components:
    - ../../../../components/volsync
    - ../../../../components/kopiur/backup
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: volsync
      namespace: security
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: home-assistant
      namespace: home
    - name: external-secrets-stores
      namespace: security
  path: ./kubernetes/apps/home/appdaemon/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      VOLSYNC_SCHEDULE: "5 0 * * *"
      VOLSYNC_LOCAL_SCHEDULE: "5 3 * * *"
      APP: *app
      VOLSYNC_CLAIM: appdaemon-config
      VOLSYNC_CAPACITY: 10Gi
      APP_UID: "1000"
      APP_GID: "1000"
