---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
  labels:
    flux.home/helm-defaults: skip
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: multus
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cni:
      binPath: /opt/cni/bin
      netPath: /etc/cni/net.d
    multus:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 512Mi
