---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: stirling-pdf

  values:
    controllers:
      stirling-pdf:
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 2.14.0@sha256:a6c5e627ceef6ed323a63da13e0d44ef68503320d1917cbc7ca2fd8e4a827aae
            env:
              TZ: "Europe/Belgrade"
              DOCKER_ENABLE_SECURITY: "false"
              SECURITY_ENABLE_LOGIN: "false"
            resources:
              requests:
                cpu: 10m
                memory: 500Mi

    service:
      app:
        controller: stirling-pdf
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.nikola.wtf"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: stirling-pdf
                port: *port

    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /configs
      tessdata:
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata
