---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vmsingle-vmetrics-r2
spec:
  sourcePVC: vmsingle-vmetrics-victoria-metrics-k8s-stack
  trigger:
    schedule: "0 0 * * *"
  restic:
    cacheCapacity: 2Gi
    cacheStorageClassName: openebs-hostpath
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    pruneIntervalDays: 7
    repository: vmsingle-vmetrics-volsync-r2
    retain:
      daily: 7
    storageClassName: miroir-local
    volumeSnapshotClassName: miroir
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmsingle-vmetrics-volsync-r2
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vmsingle-vmetrics-volsync-r2
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/vmsingle-vmetrics"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-r2-template
