---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: vmsingle-vmetrics
spec:
  compression:
    compressor: zstd
  mover:
    cache:
      capacity: 1Gi
      mode: Persistent
      storageClassName: openebs-hostpath
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  repository:
    kind: ClusterRepository
    name: r2
  retention:
    keepLatest: 3
    keepDaily: 7
  sources:
    - pvc:
        name: vmsingle-vmetrics-victoria-metrics-k8s-stack
  volumeSnapshotClassName: csi-ceph-blockpool
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: vmsingle-vmetrics
spec:
  policyRef:
    name: vmsingle-vmetrics
  schedule:
    cron: "H 0 * * *"
    timezone: Europe/Belgrade
