---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: api-token
    extraArgs:
      - --ingress-class=external
      - --gateway-name=external
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --zone-id-filter=01b2d7b9da413cc1d735fe22c719a73f
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - crd
      - ingress
      - gateway-httproute
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters:
      - "nikola.wtf"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
