---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pg
  namespace: photos
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-pg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: immich-pg
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: immich-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: aws-access-key-id
      remoteRef:
        key: immich-pg
        property: AWS_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: immich-pg
        property: AWS_SECRET_ACCESS_KEY
