---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.envoyproxy.io/httproutefilter_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: immich-share-deny
  namespace: photos
spec:
  directResponse:
    contentType: text/plain
    statusCode: 404
    body:
      type: Inline
      inline: "Not Found"
